name: imagina-services

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: products-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgrsql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pg-network

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-network

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5080:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev

  kc-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - "15432:5432"
    volumes:
      - kc_postgres_data:/var/lib/postgrsql/data
    networks:
      - kc-network

  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    command: ['start', '--optimized']
    depends_on:
      - kc-postgres
    environment:
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL: jdbc:postgresql://kc-postgres/keycloak
      KC_HEALTH_ENABLED: true
      KC_HTTP_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8180
      KC_PROXY: reencrypt
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8180:8080"
      - "8787:8787"
    networks:
      - kc-network

volumes:
  postgres_data:
  mongo_data:
  smtp4dev-data:
  kc_postgres_data:
networks:
  pg-network:
  rabbitmq-network:
  kc-network: