name: products-services

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: products-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgrsql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pg-network

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
networks:
  pg-network: