FROM quay.io/keycloak/keycloak:22.0.4 as builder

ENV KC_DB=postgres
ENV KC_FEATURES="token-exchange,scripts,preview"
WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build --cache=ispn --health-enabled=true --metrics-enabled=true

FROM quay.io/keycloak/keycloak:22.0.4

LABEL image.version=22.0.4
COPY --from=builder /opt/keycloak/ /opt/keycloak/
RUN /opt/keycloak/bin/kc.sh show-config
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]