spring:
  application:
    name: local-products-service
  datasource:
    url: jdbc:postgresql://localhost:5432/products-db
    username: postgres
    password: 12345678
  data:
    mongodb:
      uri: mongodb://localhost:27017/products
  jpa:
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
    show-sql: true
server:
  port: 8081