spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products-db
    username: postgres
    password: 12345678
  data:
    mongodb:
      uri: mongodb://localhost:27017/products
  jpa:
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true